### PR TITLE
When a project contains no folders, display a popup box instead of cr…

### PR DESCRIPTION
**Pull request by afwillia**
…ashing without error.

Wrap call to storage/projects/datasets in try() so the app doesn't crash if schematic returns an error. If an error occurs, display a pop up box.

### CODE REVIEW

**Comment by afwillia** [comment]
Consider disabling parts of the app during the error popup so that users can't proceed.

Also, provide more instructions on how to proceed. In this instance, tell user to add files to the Synapse project.

**Comment by MiekoHash** [comment]
@afwillia Which JIRA ticket is this for?

**Comment by afwillia** [comment]
@MiekoHash this would resolve https://sagebionetworks.jira.com/browse/FDS-970

**Comment by afwillia** [comment]
Reviewed in code review 12SEP2023

**Pull request merged**
