### PR TITLE
Prepare release v22.09.01

### PR DESCRIPTION
**Pull request by rrchai**
### ChangeLogs

Bugs fixes:
- #371 
- #402

Improvements:
- #323
- #374
- #376
- #388
- #389
- #398
- #407
- #411 

>**Note**
To make deployment work without `config.json` in  forks of DCA, the data-model download location also needs to be changed from `"download_url": "www/..."` to `"repo": "<repo-owner>/<repo-name>"`, i.e. "Sage-Bionetworks/data-models" in the `schematic_config.yml`.

>**Note**
If forks of DCA have been fetching `develop` to deploy for production site, please also update to use `main` or update codebase to fix the issue mentioned in #409.

### CODE REVIEW

**Review by afwillia — APPROVED** [review]
Tested it out and it looks great! Thanks 👍 👍

**Comment by milen-sage** [comment]
@rrchai thanks for the notes and the compilation of release changes, as usual very nice! Regarding the note on

> To make deployment work without config.json in forks of DCA, the data-model download location also needs to be changed from "download_url": "www/..." to "repo": "<repo-owner>/<repo-name>"...

If users don't make this change in schematic_config.yml does the deployment fail or does it go as usual except the config file is not auto generated?

**Comment by rrchai** [comment]
@milen-sage Thanks for asking.
It will result in NULL when retrieve `config$model$input$repo` information and fail cloning the data-model repo during the deployment if users don't change to use `repo`:
https://github.com/Sage-Bionetworks/data_curator/blob/675279758bd45b6084d5a063ebbe87f55dcc6dce/.github/workflows/shinyapps_deploy.yml#L76-L89

**Comment by milen-sage** [comment]
Would it be hard to have the feature backward compatible? Namely, auto-config generation is skipped but otherwise the workflow proceeds as before if schematic's config file hasn't been updated. If it's relatively easy adding that logic would be great; if not we can do it later. Just trying to avoid some communication overhead with users :)

**Comment by rrchai** [comment]
> Would it be hard to have the feature backward compatible? Namely, auto-config generation is skipped but otherwise the workflow proceeds as before if schematic's config file hasn't been updated. 

@milen-sage yes, this pr #411 will address this

**Pull request merged**
