### PR TITLE
Preprare to syn main with develop

### LINKED ISSUE #144: Compress the duplicated errors
Currently, we show all the errors, but if there are many same invalid values in the same column, those errors are duplicated and could be either compressed or have better visualization on UI.

### LINKED ISSUE #169: Upon encountering validation error, provide index of error
One of our users uploaded a 200 row manifest with many columns, and the validation report shows the following: 

Screen Shot 2021-05-25 at 4 30 48 PM

It would be helpful if it provided the index, or at least the row, of the error, so that the user can find the value quickly.

### LINKED ISSUE #187: Google sheet link is not obvious to some users
Some of our users miss the fact that a link shows up after clicking the Generate Google Sheets Link button. Maybe there is some way to make this link more obvious via a bright color or other clear call to action? 

Right now, it kind of blends in to the page.

### LINKED ISSUE #206: Disconnection when there is no existing manifest
All tests were done on the test folder located here: [syn26004567](https://www.synapse.org/#!Synapse:syn26004567). 

### Tests 
Several templates disconnected when generating the metadata template (these also disconnected on the production app) :
- [x] Bulk RNAseq level 1
- [x] scRNAseq level 1
- [x] Imaging level 2

_Originally posted by @ychae in https://github.com/Sage-Bionetworks/data_curator/issues/205#issuecomment-937340213_

### LINKED ISSUE #209: Header data dropdown didn't update input values of the dropdown in data tab
The display selections in both "tab" dropdown (project, folder, template) and "header" dropdown are synced, but the values in "tab" dropdown are not updated immediately (below). It can cause to submit to wrong folders. Looking into it today.

Screen Shot 2021-10-08 at 12 44 10 PM

### LINKED ISSUE #214: Do not populate file list for record-based data types
initial reported by @ychae 

the filenames are added in record-based manifests:

Screen Shot 2021-10-14 at 1 01 26 PM

To-fix:
- [x] Add validation in `getModelManifest` not to populate file name list for record-based manifests.

### PR DESCRIPTION
**Pull request by rrchai**
ChangeLogs
---

- #205
  - fixes #144
  - fixes #169
- #208
  - fixes #206 
- #212  
- #210 
  - fixes #209   
- #211 
  - fixes #187  
- #215 
  - fixes #214

### CODE REVIEW

**Comment by ychae** [comment]
#211 the google sheet link is way more obvious now (the pop-up makes it impossible to ignore lol)

**Comment by milen-sage** [comment]
> I should also make it clear that I specifically selected a folder that had files and not a folder that had records data to see what would happen.

@ychae that's useful! The SOP assumes no files in 'record-based' datasets, so that's a scenario that'd be attributed to user error. However, we should handle it (and we used to) we shouldn't populate the Filename column if a 'record-based' (i.e. clinical template) has been selected. 

@ychae is the Filename column populated with filenames?

@rrchai could you confirm that the DC app doesn't send a list of filenames to schematic if the selected template type is one of the clinical or biospecimen types (i.e. type: clinical in the config file)?

**Comment by ychae** [comment]
> @ychae is the Filename column populated with filenames?

@milen-sage yep, the filenames are there:
Screen Shot 2021-10-14 at 1 01 26 PM

**Comment by rrchai** [comment]
@milen-sage 

The DC app is sending the filename list no matter what datatype is for now:

https://github.com/Sage-Bionetworks/data_curator/blob/aa683aee385750991011efbc642bd61a48315682/server.R#L212-L217

Would you like to add this validation on front-end or back-end? I could simply change one line code ` ifelse(template_type == "assay, filenames = as.list(names(datatype_list$files),  list())` to the #Line-215

**Comment by milen-sage** [comment]
Let's test and confirm, and we should be good to go! @ychae could you validate?

**Review by milen-sage — APPROVED** [review]

**Comment by ychae** [comment]
> Let's test and confirm, and we should be good to go! @ychae could you validate?

Validated! Tested on three different clinical templates (demographics, family history, and molecular test) on a folder with files (syn26004567) and there were no filenames in the templates 🎉✅

**Pull request merged**
