### PR TITLE
Address changes on validateModelManifest() from schematic

### PR DESCRIPTION
**Pull request by rrchai**
- address #309 

- disable great expectation
- only get errors - 1st element of output list
- rename function params

---
Do not merge until https://github.com/Sage-Bionetworks/schematic/pull/614 is merged to develop of schematic

### CODE REVIEW

**Comment by rrchai** [comment]
Note: this pr has not tested with new cross-validation rules yet. The changes here can make the DCA works as before to address the changes on function `validateModelManifest`. 

To test new cross-validation rule, we would need to add new cross-validation rules to data-model and update DCA codes to display appropriate errors for users. -> it will be saved for another PR, when the error message for cross-validation from schematic is settle.

**Comment by allaway** [comment]
Ah, I was just poking around to see if you had already solved this new issue in `annotation_status`, looks like this PR is to address that? 

```

2022-04-28T22:19:16.242590+00:00 shinyapps[5711947]: Warning: Error in validationResult: object 'annotation_status' not found
2022-04-28T22:19:16.242697+00:00 shinyapps[5711947]:   13: fn
2022-04-28T22:19:16.242649+00:00 shinyapps[5711947]:   15: <Anonymous>
2022-04-28T22:19:16.242749+00:00 shinyapps[5711947]:    8: retry
2022-04-28T22:19:16.242783+00:00 shinyapps[5711947]:    7: connect$retryingStartServer
2022-04-28T22:19:16.242816+00:00 shinyapps[5711947]:    6: eval
2022-04-28T22:19:16.242877+00:00 shinyapps[5711947]:    5: eval
```

**Comment by rrchai** [comment]
@allaway yes, the `develop` of schematic is recently updated on validation function. To quick fix your issue, you could just add [[1]] at the end of [this function](https://github.com/Sage-Bionetworks/data_curator/blob/4d174c1ec2bb577f6ab638406f4a539afdb0233a/server.R#L285-L288). Or you could test with this pr.

**Comment by allaway** [comment]
Thanks! I will pull in the changes from this PR and let you know how it goes!

**Review by allaway — APPROVED** [review]
These changes work swimmingly for me; was able to pass validation and submit annotations without any problem.

**Pull request merged**
