### PR TITLE
Fix issues from DCA using the latest schematic

### PR DESCRIPTION
**Pull request by rrchai**

### CODE REVIEW

**Comment by rrchai** [comment]
It looks like using "both" will raise this error:
```
Value at [0,42] was not a valid STRING. String '5aae303a-52d6-460f-a626-6e7bd0c98d28' exceeds the maximum length of 30 characters.
```

**Review by milen-sage — APPROVED** [review]
We can have this configurable instead of hard-coded later on. Since this is a hotfix definitely don't need to worry about it now.

After merging could you test and see if manifests get generated, validated and submitted w/o crashes, e.g. generating manifests for real projects to confirm project is still properly reflected in manifest sheet and validating + submitting a couple of manifests to Center A? 

Thanks @rrchai !!!

And let's bring up this debugging experience as an example during our retrospective for FAIR Data's sprint. It looks like we can improve a few things around schematic releases & respective communication and documentation. E.g. our current setup requires us reaching out to other DCA stakeholders to announce changes in schematic that may break their apps; I think currently these changes are insufficiently documented & communicated. With the new release setup, a lot of that will get fixed, but it'd still be good to discuss.

**Comment by milen-sage** [comment]
> It looks like using "both" will raise this error:
> 
> ```
> Value at [0,42] was not a valid STRING. String '5aae303a-52d6-460f-a626-6e7bd0c98d28' exceeds the maximum length of 30 characters.
> Detailed traceback:
>   File "/home/rchai/ShinyApps/data_curator/.venv/lib/python3.8/site-packages/schematic/store/synapse.py", line 650, in associateMetadataWithFiles
>     manifest_synapse_table_id, manifest = self.upload_format_manifest_table(
>   File "/home/rchai/ShinyApps/data_curator/.venv/lib/python3.8/site-packages/schematic/store/synapse.py", line 513, in upload_format_manifest_table
>     table = self.syn.store(Table(schema, manifest))
>   File "/home/rchai/ShinyApps/data_curator/.venv/lib/python3.8/site-packages/synapseclient/client.py", line 1002, in store
>     return obj._synapse_store(self)
>   File "/home/rchai/ShinyApps/data_curator/.venv/lib/python3.8/site-packages/synapseclient/table.py", line 1909, in _synapse_store
>     return copied_self._update_self(syn)
>   File "/home/rchai/ShinyApps/data [... truncated]
>   [No stack trace available]
> ```

Acknowledged @rrchai, we'll take a look into it. Meanwhile could you try setting it to "table"?

**Comment by rrchai** [comment]
@milen-sage  setting to "table" has the same error. I notice something specious:

According to https://github.com/Sage-Bionetworks/schematic/blob/a9301999d407b10caa7370478ae96cff32f32472/schematic/store/synapse.py#L618-L625, When I was using manifest type, such as "assay",  the `associateMetadataWithFiles` is supposed to raise ValueError, which I didn't get ...

I double checked I used the latest version of schematic, keep looking into it

**Comment by milen-sage** [comment]
@rrchai yes, interesting that you didn't get the value error. 

I guess one last option to try is setting the manifest record type to "entity". If that results in the same error, we can take a look at this further in schematic on our end. 

> String '5aae303a-52d6-460f-a626-6e7bd0c98d28' exceeds the maximum length of 30 characters.

It looks like this^ error has to do with how an existing Synapse fileview schema handles a new type of internal bookkeeping ID that we are introducing. It shouldn't be too hard to fix.

@mialy-defelice heads up that this may be coming your way.

**Comment by rrchai** [comment]
@milen-sage I can submit a [testing manifest](https://www.synapse.org/#!Synapse:syn25953343) using "entity"

**Comment by mialy-defelice** [comment]
> 

Hey @rrchai  [this PR ](https://github.com/Sage-Bionetworks/schematic/pull/666) that was pushed yesterday should address the string length issue.

Ill look into the Value Error, but I can also limit the types of entries so that should prevent inclusion of something like "assay". I think its already limited in the API.

**Comment by milen-sage** [comment]
> @milen-sage I can submit a [testing manifest](https://www.synapse.org/#!Synapse:syn25953343) using "entity"

@rrchai great! let's go with "entity" for now and when the PR @mialy-defelice mentioned is merged we can test again.

Is manifest sheet generation and validation ow working as expected with the "entity" option?

**Comment by rrchai** [comment]
> Is manifest sheet generation and validation ow working as expected with the "entity" option?

@milen-sage the validation functions work as expected. For the generation function, nice bug coming:

I tried to generate "scrna-level1" and "biospecimen", both cause app to crash and raise below error.
```
Warning: Error in py_call_impl: AttributeError: 'NoneType' object has no attribute 'lower'

Detailed traceback:
  File "/home/rchai/ShinyApps/data_curator/.venv/lib/python3.8/site-packages/schematic/models/metadata.py", line 150, in getModelManifest
    return mg.get_manifest(
  File "/home/rchai/ShinyApps/data_curator/.venv/lib/python3.8/site-packages/schematic/manifest/generator.py", line 1462, in get_manifest
    empty_manifest_url = self.get_empty_manifest()
  File "/home/rchai/ShinyApps/data_curator/.venv/lib/python3.8/site-packages/schematic/manifest/generator.py", line 1249, in get_empty_manifest
    manifest_url = self._create_empty_gs(
  File "/home/rchai/ShinyApps/data_curator/.venv/lib/python3.8/site-packages/schematic/manifest/generator.py", line 1186, in _create_empty_gs
    requests_body = self._create_requests_body(
  File "/home/rchai/ShinyApps/data_curator/.venv/lib/python3.8/site-packages/schematic/manifest/generator.py", line 1143, in _create_requests_body
    create_dropdown [... truncated]
  [No stack trace available]
```

ps. When I tested generation yesterday, I was on [b13483c](https://github.com/Sage-Bionetworks/schematic/commits/develop) and it worked as expected. I assume the changes afterwards might relate to this^ issue.

**Comment by mialy-defelice** [comment]
> > Is manifest sheet generation and validation ow working as expected with the "entity" option?
> 
> @milen-sage the validation functions work as expected. For the generation function, new bug alert :)
> 
> I tried to generate "scrna-level1" and "biospecimen", both cause app to crash and raise below error.
> 
> ```
> Warning: Error in py_call_impl: AttributeError: 'NoneType' object has no attribute 'lower'
> 
> Detailed traceback:
>   File "/home/rchai/ShinyApps/data_curator/.venv/lib/python3.8/site-packages/schematic/models/metadata.py", line 150, in getModelManifest
>     return mg.get_manifest(
>   File "/home/rchai/ShinyApps/data_curator/.venv/lib/python3.8/site-packages/schematic/manifest/generator.py", line 1462, in get_manifest
>     empty_manifest_url = self.get_empty_manifest()
>   File "/home/rchai/ShinyApps/data_curator/.venv/lib/python3.8/site-packages/schematic/manifest/generator.py", line 1249, in get_empty_manifest
>     manifest_url = self._create_empty_gs(
>   File "/home/rchai/ShinyApps/data_curator/.venv/lib/python3.8/site-packages/schematic/manifest/generator.py", line 1186, in _create_empty_gs
>     requests_body = self._create_requests_body(
>   File "/home/rchai/ShinyApps/data_curator/.venv/lib/python3.8/site-packages/schematic/manifest/generator.py", line 1143, in _create_requests_body
>     create_dropdown [... truncated]
>   [No stack trace available]
> ```
> 
> ps. When I tested generation yesterday, I was on [b13483c](https://github.com/Sage-Bionetworks/schematic/commits/develop) and it worked as expected. I assume the changes afterwards might relate to this^ issue.

I am very confusingly running into this error too :(

**Comment by mialy-defelice** [comment]
@rrchai @GiaJordan 

Gianna, Rong and I have started to experience an error when trying to generate manifests. I was testing the manifest generate API endpoint, Rong is testing the DCA...

This is my full stack:
```Traceback (most recent call last):
  File "/Users/mialydefelice/Library/Caches/pypoetry/virtualenvs/schematicpy-gze8NI9f-py3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/Users/mialydefelice/Library/Caches/pypoetry/virtualenvs/schematicpy-gze8NI9f-py3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/Users/mialydefelice/Library/Caches/pypoetry/virtualenvs/schematicpy-gze8NI9f-py3.9/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mialydefelice/Library/Caches/pypoetry/virtualenvs/schematicpy-gze8NI9f-py3.9/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/mialydefelice/Library/Caches/pypoetry/virtualenvs/schematicpy-gze8NI9f-py3.9/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mialydefelice/Library/Caches/pypoetry/virtualenvs/schematicpy-gze8NI9f-py3.9/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mialydefelice/Library/Caches/pypoetry/virtualenvs/schematicpy-gze8NI9f-py3.9/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mialydefelice/Library/Caches/pypoetry/virtualenvs/schematicpy-gze8NI9f-py3.9/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mialydefelice/Library/Caches/pypoetry/virtualenvs/schematicpy-gze8NI9f-py3.9/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mialydefelice/Library/Caches/pypoetry/virtualenvs/schematicpy-gze8NI9f-py3.9/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/mialydefelice/Library/Caches/pypoetry/virtualenvs/schematicpy-gze8NI9f-py3.9/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mialydefelice/Library/Caches/pypoetry/virtualenvs/schematicpy-gze8NI9f-py3.9/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mialydefelice/Library/Caches/pypoetry/virtualenvs/schematicpy-gze8NI9f-py3.9/lib/python3.9/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
  File "/Users/mialydefelice/Library/Caches/pypoetry/virtualenvs/schematicpy-gze8NI9f-py3.9/lib/python3.9/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "/Users/mialydefelice/Library/Caches/pypoetry/virtualenvs/schematicpy-gze8NI9f-py3.9/lib/python3.9/site-packages/connexion/decorators/validation.py", line 399, in wrapper
    return function(request)
  File "/Users/mialydefelice/Library/Caches/pypoetry/virtualenvs/schematicpy-gze8NI9f-py3.9/lib/python3.9/site-packages/connexion/decorators/parameter.py", line 116, in wrapper
    return function(**kwargs)
  File "/Users/mialydefelice/Documents/schematic_b/schematic/api/routes.py", line 143, in get_manifest_route
    result = create_single_manifest(data_type = dt)
  File "/Users/mialydefelice/Documents/schematic_b/schematic/api/routes.py", line 118, in create_single_manifest
    result = manifest_generator.get_manifest(
  File "/Users/mialydefelice/Documents/schematic_b/schematic/schematic/manifest/generator.py", line 1438, in get_manifest
    return self.get_empty_manifest(json_schema_filepath=json_schema)
  File "/Users/mialydefelice/Documents/schematic_b/schematic/schematic/manifest/generator.py", line 1249, in get_empty_manifest
    manifest_url = self._create_empty_gs(
  File "/Users/mialydefelice/Documents/schematic_b/schematic/schematic/manifest/generator.py", line 1186, in _create_empty_gs
    requests_body = self._create_requests_body(
  File "/Users/mialydefelice/Documents/schematic_b/schematic/schematic/manifest/generator.py", line 1143, in _create_requests_body
    create_dropdown = self._request_dropdown_or_multi(
  File "/Users/mialydefelice/Documents/schematic_b/schematic/schematic/manifest/generator.py", line 950, in _request_dropdown_or_multi
    validation_body = self._get_column_data_validation_values(
  File "/Users/mialydefelice/Documents/schematic_b/schematic/schematic/manifest/generator.py", line 257, in _get_column_data_validation_values
    if self.alphabetize.lower().startswith('a'):
AttributeError: 'NoneType' object has no attribute 'lower'

From what I can tell this was introduced during [this](https://github.com/Sage-Bionetworks/schematic/commit/0f13bc1b76c0d1d8c23f5fec222a508caf64e72e#diff-6cad414bbd1992ca1cf5ece936af1a8fb6874496d306d3598397247f9b4b9457) PR.

**Comment by GiaJordan** [comment]
@mialy-defelice I noticed that as well earlier today. It's addressed in PR [#643](https://github.com/Sage-Bionetworks/schematic/pull/669). For now if you specify `'ascending' `or `'a' `for the `-av` parameter It'll generate fine, but once this PR is merged it will do ascending as the default and you won't have to specify. I've let @milen-sage know as well. Sorry for the inconvenience!

**Comment by mialy-defelice** [comment]
> @mialy-defelice I noticed that as well earlier today. It's addressed in PR [#643](https://github.com/Sage-Bionetworks/schematic/pull/669). For now if you specify `'ascending' `or `'a' `for the `-av` parameter It'll generate fine, but once this PR is merged it will do ascending as the default and you won't have to specify. I've let @milen-sage know as well. Sorry for the inconvenience!

Ahh okay, perfect! Can you add this option to the API as well?

**Comment by GiaJordan** [comment]
> Ahh okay, perfect! Can you add this option to the API as well?

[sure](https://github.com/Sage-Bionetworks/schematic/pull/669/commits/7eda84ebcee818751f417f4eda7be73ca87e5099)!

**Comment by GiaJordan** [comment]
@mialy-defelice @rrchai The PR has been merged, you should be good now!

**Comment by milen-sage** [comment]
@rrchai it looks like we are testing & fixing all the code today! thanks again!! 🤞 the last couple of updates resolve the situation.

**Comment by rrchai** [comment]
@milen-sage @mialy-defelice @GiaJordan 
Thanks all for debugging !!! I am going to merge this PR now and update the app soon

**Comment by milen-sage** [comment]
@rrchai just confirming all latest changes that we discussed here have been added to the `develop` branch of schematic.

**Pull request merged**
