### PR TITLE
Update UI error message for cross-validation errors

### PR DESCRIPTION
**Pull request by rrchai**
- address #309

### CODE REVIEW

**Review by afwillia — APPROVED** [review]

**Comment by rrchai** [comment]
@afwillia It is actually not ready to be merged yet. It has not captured the error messages for cross-manifest rules.

**Comment by rrchai** [comment]
@afwillia Don't worry about restoring it and we can make another PR to update it later on. Are you working on this feature?

**Comment by afwillia** [comment]
@rrchai ah, my bad. Yeah, I am trying to update the error messages you mentioned while you're out.

**Comment by rrchai** [comment]
@afwillia No worries at all. Thanks for helping. Feel free to update the error messages and I will be also back to work on DCA later today.

**Comment by afwillia** [comment]
@rrchai okay great, thanks for the heads up. Good to hear you're back!

**Pull request merged**
