### PR TITLE
Prepare release v22.11.3

### PR DESCRIPTION
**Pull request by rrchai**
### ChangeLogs

Bugs fixes:
- #419
- #421
- #439

Improvements:

- #420

Features:
- #430

### CODE REVIEW

**Comment by milen-sage** [comment]
@rrchai let's out a hold on this release. I was testing the dashboard UI and it looks like when a project is selected (e.g. HTAN BU), the dataset folders dropdown doesn't get populated properly: I only see the archive dataset folder. Let me know if you can replicate.

**Comment by milen-sage** [comment]
Also, we can rename it to 22.11.1.

**Comment by rrchai** [comment]
@milen-sage  Good catch! It was bug from #419. `Ifelse` in r only return 1st item of folder list. It will be fixed in #430.

**Review by afwillia — APPROVED** [review]
LGTM!

**Comment by rrchai** [comment]
Based on the discussion, this pr is ready to be merged into `develop` and prepare for the release.

**Comment by rrchai** [comment]
merged this pr into `main` for next release.

**Pull request merged**
