### PR TITLE
Release v22.07.1

### PR DESCRIPTION
**Pull request by rrchai**
ChangeLogs:
--- 

### New features:
 1. Change manifest types  to "file" & "record" and enable to upload manifest as table and
  - #318
  - #337 
  2. Enable the cross-manifest validation and update validation UI
  - #315 
  - #347
### Setup:
- #310
- #313

### Bugs fix:
- #319 
- #320

### CODE REVIEW

**Comment by milen-sage** [comment]
@rrchai just confirming, this version of the DCA uses the develop branch of schematic right?

**Comment by milen-sage** [comment]
@rrchai just chatting with Giana, it looks like the cross-validation functionality is not merged in develop yet. We will do that on Mon after we release the current `develop` codebase in schematic to pypi. We can release the DCA after that merge.

**Comment by rrchai** [comment]
@milen-sage right! Thanks for  checking. We will hold this release until the cross-manifest functionality is merged to develop then.

**Comment by milen-sage** [comment]
@rrchai the schematic `develop` branch now contains the cross-validation code needed for this release. Feel free to release!

**Pull request merged**
