### PR TITLE
Update New Virtual Env Setup After Testing on Server

### PR DESCRIPTION
**Pull request by rrchai**
This PR address some spotted issues while testing #244 and also provides some improvements:

- [x] We are replacing `conda` with `virtual` environment and each folder has its own virtual env. In this case, it is not necessary to have the customizable "conda env name" in the `config.yaml` anymore. Simply, we can deprecate the `conda` approach and just ask users to use `.venv`. It also matches the setup for the workflow of deployment -> [e0121eb](https://github.com/Sage-Bionetworks/data_curator/commit/e0121ebcc7ee8c3b9fb9164ec68d4b2647b36443)
- [x] It is not required to zip files for local testing. Check if `.venv` already exists before unzip file in `global.R` -> [31abbe2](https://github.com/Sage-Bionetworks/data_curator/commit/31abbe2513c0453d01f8bdce0cf9b185f836c802)
- [x] `app_url` is missing that causes app crashes -> [c3ff18c](https://github.com/Sage-Bionetworks/data_curator/commit/c3ff18cbba45597411b4e08d945fcf42885d3b41)
- [x] Remove some unused r packages: `ggplot`, `jsonr`, `purrr`, `plotly`. We can add the package back if we use it later.
- [x] Deprecate `renv` since `install-pkgs.R` is used in the workflow to speed up the installation. -> [e37edcb](https://github.com/Sage-Bionetworks/data_curator/pull/250/commits/e37edcb805c355ff50023ef8c73857e6cf5e0945)
- [x] Add versions # to R dependencies in `install-pkgs.R` -> [5e4e1c1](https://github.com/Sage-Bionetworks/data_curator/pull/250/commits/5e4e1c1ccffd0ed58eb443333270336ca9bf2cdf)

--- 
### Schematic Dependencies
@milen By spinning up a new instance with virtual env setup, if I use `poetry install`, I noticed by installing latest versions of some dependencies will cause app crash:

- App crashes due to a `numpy` error. The schematic install latest version `1.22.0`. If I manually install `pip install numpy==1.19.3` again, it will solve this issue. Is it possible to let schematic install defined versions of dependencies using `poetry install`?
```
Error in py_run_file_impl: RuntimeError: The current Numpy installation ('/home/rchai/ShinyApps/dc-test/.venv/lib/python3.8/site-packages/numpy/__init_
_.py') fails to pass simple sanity checks. This can be caused for example by incorrect BLAS library being linked in, or by mixing package managers (pip, conda, 
apt, ...). Search closed numpy issues for similar problems.
```

### CODE REVIEW

**Review by milen-sage — COMMENTED** [review]
@rrchai going through steps 4 and 5 doesn't result in the errors you bumped into in #250?

**Comment by rrchai** [comment]
@milen-sage After testing with and without requirements.txt:

1. Without using `requirements.txt` and use `poetry install` directly from `schematic` repo:

          I can reproduce the same error which indicates the incompatible `numpy` version.

2. Run `pip install -r requirements.txt` to install dependencies and then run `poetry install`:

          The setup can make app work successfully.

The reason is that if we skip `requirements.txt` which specifies `numpy==1.19.0` and use `poetry install` directly, it will look for `numpy==1.21.1`  in [poetry.lock](https://github.com/Sage-Bionetworks/schematic/blob/5e933c12e387fec942bed24cd9586e7b3a9bf954/poetry.lock#L527) instead.

**Comment by rrchai** [comment]
With the approach 2 ^, it did raise some warnings:

- when install dependencies from `requirements.txt`:

```          
ERROR: google-api-core 1.26.3 has requirement google-auth<2.0dev,>=1.21.1, but you'll have google-auth 2.3.3 which is incompatible.
ERROR: schematicpy 1.0.0 has requirement click<8.0.0,>=7.1.2, but you'll have click 8.0.3 which is incompatible.
ERROR: schematicpy 1.0.0 has requirement google-api-python-client<2.0.0,>=1.12.8, but you'll have google-api-python-client 2.35.0 which is incompatible.
ERROR: schematicpy 1.0.0 has requirement google-auth-httplib2<0.0.5,>=0.0.4, but you'll have google-auth-httplib2 0.1.0 which is incompatible.
ERROR: schematicpy 1.0.0 has requirement graphviz<0.17,>=0.16, but you'll have graphviz 0.19.1 which is incompatible.
ERROR: schematicpy 1.0.0 has requirement synapseclient<2.4,>=2.3, but you'll have synapseclient 2.5.1 which is incompatible.
```
- when `potery install` the `schematicpy` package:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
schematicpy 1.0.0 requires synapseclient<2.4,>=2.3, but you have synapseclient 2.5.1 which is incompatible.
```

**Comment by rrchai** [comment]
@afwillia 

I have updated `REAMDE` to remove the `conda/renv` setup and make `pip install -r requirements.txt` clearer. Would it be possible to review the instructions in the updated [README](https://github.com/Sage-Bionetworks/data_curator/blob/update-%23244/README.md) and the changes of this PR when you have time. Please feel feel to let me know if there are any questions.

The PR is based on your branch #244 and it will merge it to your branch.

**Comment by afwillia** [comment]
@rrchai this looks great to me. I think the README is much easier to understand with these changes. I'll go ahead and merge it

**Pull request merged**
