### PR TITLE
Add UI dashboard - ChangeLog

### LINKED ISSUE #174: Mockup User-interface Dashboard - latest
There are already some issues open related to this feature: #12, #14, #15, #107. Here I just collected notable information from previous issues and start to mock up this feature.

In general, this feature should provide user-interface dashboard that helps users to notice their metadata submission progress, and get sense of what other metadata they should/can provide. In addition, this feature is also able to validate users' metadata and display some information to facilitate their data curation process. 

I will start to mock up this feature by splitting three tabs and below is some details for this feature:
- First of all, the feature should be optional for users. One of the reasons could be because extracting information from manifest may require downloading the files. It could cause much time to run for users who have a large number of files. To achieve this, we can initially hide the feature and let users use button to control. 
- The feature is tab panel with three tabs: "selected template", "uploaded files", "metadata validation" (I'm bad at naming). The tab panel should be hidden in the second tab, **select your dataset**,  of app.

1. ["selected template"] :label:: this tab will demonstrate what metadata are required for the selected template 
  :bulb: checklist + simple network
2. ["uploaded files"] :label:: this tab will show all required metadata for uploaded manifests in the selected project 
  :bulb: tree
3. ["metadata validation"] :label:: this tab will validate users' uploaded metadata (provide button to initiate)
  :bulb: tubular data table
    - whether metadata is out of data, aka, the metadata come with any errors from `validateModelManifest`
    - we could also add more validation results similar with what [current dashboard](http://htan_dashboard.surge.sh/syn22124336.html) has

Besides, we could add some `valueBox` to show overall stats about users progress in each project, such as total number of uploaded manifests; total progress % ( this will required a fixed number to avoid confusion and I will just use total number of templates in `schema.json` for now).

I will create different PRs for each tab. Please feel free to leave suggestions here or in the front-end meeting. 
@milen-sage @sujaypatil96

### PR DESCRIPTION
**Pull request by rrchai**
- fixes #174

### ChangeLogs
- [x] #182 
- [x] #183 
- [x] #184 
- [x] ~~#185~~ 
- [x] #186
- [x] #245
- [x] #304  
- [x] #308
- [x] #305
- [x] #314 
- [x] #361 
  - first attempt: fail - request reach maximum attempts
  - second attempt: still fail but with more testings and insights - see #361 
- [x] bug report: break the dashboard: #366

Address feedbacks from https://github.com/Sage-Bionetworks/data_curator/milestone/21
### Preview
_testing on: https://sagebio.shinyapps.io/data_curator-demo_ (this instance is not updating anymore 10/27/2022)

- [x] CURRENTLY USING HTAN FOR DEMO AND REMEMBER TO CHANGE BACK TO USE GENERAL CONFIGURATION 

--- 
## File structure related with dashboard
Screen Shot 2022-10-28 at 11 28 08 AM

### CODE REVIEW

**Comment by rrchai** [comment]
blocked by this error with latest setup in shinyServer
```
Error: package or namespace load failed for ‘networkD3’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/rchai/R/x86_64-pc-linux-gnu-library/3.6/igraph/libs/igraph.so':
  libglpk.so.40: cannot open shared object file: No such file or directory
```

**Comment by rrchai** [comment]
After the discussion with @milen-sage today, I will do some follow-up bug fixes and improvements on the validation tab.

**Comment by milen-sage** [comment]
@rrchai just confirming, I can add a couple of commits with minor text changes to [this branch ](https://github.com/Sage-Bionetworks/data_curator/tree/feat-UI-dashboard) as part of this PR? Thanks!

**Comment by rrchai** [comment]
redirect to #430 (renamed with `develop` prefix for branch name)

**Pull request closed without merging**
